my:
    resource: "@MyBundle/Resources/config/routing.yml"
    prefix:   /

application:
    resource: "@applicationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
